export enum ChannelType {
    Intensity   = 0,
    Pan         = 1,
    Tilt        = 2,
    PanFine     = 3,
    TiltFine    = 4,
    PTSpeed     = 5,
    Zoom        = 6,
    Focus       = 7,
    Shutter     = 8,
    Red         = 9,
    Green       = 10,
    Blue        = 11,
    White       = 12,
    WarmWhite   = 13,
    ColorTemp   = 14,
    Strobe      = 15,
    Prism       = 16,
    Effect      = 17,
    None        = 18,
}